interface Skill {
  id: number;
  name: string;
  icon: string;
  level: number;
  category: string;
  color: string;
}

export const SKILLS: Skill[] = [
  {
    id: 1,
    name: 'React',
    icon: '/example.jpg',
    level: 70,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 2,
    name: 'JavaScript',
    icon: '/example.jpg',
    level: 80,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 3,
    name: 'TypeScript',
    icon: '/example.jpg',
    level: 70,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 3,
    name: 'Vue3',
    icon: '/example.jpg',
    level: 40,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 4,
    name: 'Next',
    icon: '/example.jpg',
    level: 70,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 5,
    name: 'HTML5',
    icon: '/example.jpg',
    level: 95,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 6,
    name: 'CSS',
    icon: '/example.jpg',
    level: 90,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 7,
    name: 'Tailwind CSS',
    icon: '/example.jpg',
    level: 90,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 8,
    name: 'Bootstrap',
    icon: '/example.jpg',
    level: 80,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 9,
    name: 'Ant Design / Shadcn UI',
    icon: '/example.jpg',
    level: 80,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 10,
    name: 'Framer Motion',
    icon: '/example.jpg',
    level: 80,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 11,
    name: 'Node',
    icon: '/example.jpg',
    level: 60,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 12,
    name: 'Express',
    icon: '/example.jpg',
    level: 50,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 13,
    name: 'MySQL',
    icon: '/example.jpg',
    level: 50,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 14,
    name: 'Nest',
    icon: '/example.jpg',
    level: 40,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 15,
    name: 'Prisma',
    icon: '/example.jpg',
    level: 80,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 16,
    name: 'Version Control Git',
    icon: '/example.jpg',
    level: 90,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 17,
    name: 'Swagger',
    icon: '/example.jpg',
    level: 70,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 18,
    name: 'Postman',
    icon: '/example.jpg',
    level: 80,
    category: 'Backend',
    color: '#339933',
  },
];
